Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,8 @@ jobs:
           cache: true
       - name: Run Tests
         shell: bash
-        run: flutter test || echo "Warning: Tests failed, but proceeding..."
+        run: |
+          flutter test || echo "Warning: Tests failed, but proceeding..."
 
   build:
     needs: test
@@ -38,7 +39,7 @@ jobs:
             os: macos-15
     runs-on: ${{ matrix.os }}
     steps:
-      - name: Checkout
+      - name: Checkout main repository
         uses: actions/checkout@v4
         with:
           persist-credentials: false
@@ -50,7 +51,9 @@ jobs:
           git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
 
       - name: Update submodules
-        run: git submodule update --init --recursive
+        shell: bash
+        run: |
+          git submodule update --init --recursive
 
       - name: Setup Go
         uses: actions/setup-go@v5
@@ -81,13 +84,11 @@ jobs:
             sudo apt-get update && sudo apt-get install -y make
           fi
 
-      - name: Flutter Pub Get
-        run: flutter pub get
-
       - name: Build App
         shell: bash
         run: |
           export PATH="$PATH":"$HOME/.pub-cache/bin"
+          flutter pub get
           make ${{ matrix.platform }}-release
 
       - name: Prepare Artifacts
